[build]
builder = "nixpacks"

[build.envVars]
NIXPACKS_NODE_VERSION = "18"

[deploy]
startCommand = "npm run start:prod"
healthcheckPath = "/"
healthcheckTimeout = 100
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 3
